### PR TITLE
Add ability to provide a mapper name in Env#read

### PR DESCRIPTION
**Pull request by solnic**
refs #122
cc @aflatter

### CODE REVIEW

**Comment by solnic** [comment]
that would couple relation with mapper :( suddenly it would know about its existence

**Comment by solnic** [comment]
BTW I should mention a couple of things just to clarify:

- `rom.relations` are exposed because of a lack of certain interfaces; eventually I would like to have some higher-level interfaces exposed by `env` so that you don't have to access relations directly. For instance I can easily see a separate interface for aggregations (max, min, count etc.)
- `Reader` object is a top-level interface for reading defined relations via mappers. It is an enumerable object that only exposes publicly available relations and *excludes native query DSLs or any other interfaces provided by the adapter layer*

I have to admit this my little experiment and maybe this approach will turn out to be too strict and not *flexible* enough (being enforced to specify relations for every part of your system that needs data can be annoying in very simple applications). So this is something that might be changed. Regardless - I like reader idea as a higher-level object used only for accessing relations, hence I'd like to have this feature to be part of the reader API, not relation. Especially that, like I already mentioned, Relation doesn't know about the mappers and I believe it should stay like that.

**Comment by solnic** [comment]
OK so now it's:

``` ruby
rom.read(:users).with_mapper(:prefixer)
```

HAPPY?!!??!?!?! ;)

**Comment by aflatter** [comment]
Haha, let's go with that :+1: Thanks for explaining, you successfully managed to convince me not to :fire: reader. ;-)

**Comment by solnic** [comment]
:relieved:

**Pull request merged**
