### PR TITLE
Add `combine` interface to mapping DSL

### PR DESCRIPTION
**Pull request by solnic**
### TODO

- [x] add support for `combine` interface in Mapping DSL
- [x] add support for setting model on combined relations
- [x] make sure that nested combined relations work too
- [x] make sure other transformations can be applied to combined relations (ie combine + wrap inside)

### CODE REVIEW

**Comment by solnic** [comment]
:tada: :tada: :tada: 

/cc @cflipse @gotar @maetl @AMHOL

**Comment by gotar** [comment]
+1 :clap:

**Comment by solnic** [comment]
OK I also added support for collapsing array into a hash. I also checked it against rom-sql...works like a charm.

So, any thoughts? I'd like to merge this in :)

**Comment by cflipse** [comment]
Looks good.

Oof, that's a lot of setup in the spec.  :)

:+1:

**Comment by solnic** [comment]
@cflipse my strategy has been:

- get stuff working based on mapper integration test
- test it out in the wild
- move from integration down to `unit/rom/process/transproc` with more detailed specs and potentially simply previous integration specs to only test the high level stuff with a happy-path scenario

Eventually mapper integration tests will be greatly simplified and complex logic will be tested in the unit tests. It's an ongoing process.

**Comment by solnic** [comment]
This is now merged. If you have any more comments please do let me know. I'll incorporate any feedback directly on master...now I just gotta move on due to my time constraints :(

**Pull request merged**
