### PR TITLE
Support automatic schema inferring

### PR DESCRIPTION
**Pull request by flash-gordon**

### CODE REVIEW

**Comment by flash-gordon** [comment]
Looking on Travis I wonder why bundler tries to install activerecord even if it was told not to install `benchmarks` section. Strange.

**Comment by solnic** [comment]
I've noticed that too, maybe we're not using the right option?

**Comment by flash-gordon** [comment]
I don't know, I guess it can be caused by using custom `script` option. Don't worry, I'll figure that out tonight :)

**Comment by flash-gordon** [comment]
@solnic ahahah, we depends on activesupport [here](https://github.com/rom-rb/rom/blob/master/Gemfile#L18) ¯\\\_(ツ)_/¯
I'll try to remove it...

**Comment by solnic** [comment]
@flash-gordon impossible, inflecto doesn't have dependencies

**Comment by flash-gordon** [comment]
@solnic haha, 18th line was removed :) https://github.com/rom-rb/rom/commit/c66b6ecedf9122d386088120a7c5a544bede61df

**Comment by solnic** [comment]
@flash-gordon ugh sorry /me disappears from github

**Pull request merged**
