### PR TITLE
[WIP] Command Graph

### LINKED ISSUE #214: Extend Command API with a support for persisting object graphs
## API idea

``` ruby
users = rom.command(:users).create
tasks = rom.command(:tasks).create

command = users.combine(tasks).call(
  [name: 'Jane', [{ title: 'One' }, { title: 'Two' }]
)

 # returns inserted tuples in nested array ready for potential mapping
command.call
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/13192465-extend-command-api-with-a-support-for-persisting-object-graphs?utm_campaign=plugin&utm_content=tracker%2F155789&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F155789&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by solnic**
This adds `combine` interface to Commands that allows you to build a command which will return a graph that can be mapped using combine mapping just like in case of relations.

closes #214

### CODE REVIEW

**Comment by solnic** [comment]
Thoughts? /cc @maetl @AMHOL @gotar @nepalez @cflipse

**Comment by gotar** [comment]
+1

**Comment by AMHOL** [comment]
:+1: nice work

**Comment by nepalez** [comment]
yes, like it too

**Comment by cflipse** [comment]
:+1:

**Comment by solnic** [comment]
Hah awesome :) I'm gonna improve tests and merge it in tomorrow probably

**Pull request merged**
