### PR TITLE
Add Result#and_then and Result#or_else as per #104

### PR DESCRIPTION
**Pull request by pdswan**
Considered adding runtime checks to make sure the value returned from the block is a `Result` as per the type signatures in the [Rust docs](http://doc.rust-lang.org/0.11.0/std/result/index.html), but decided to poll opinions first.

### CODE REVIEW

**Comment by solnic** [comment]
Oh lovely! Could you also write an integration spec showing off how it looks? Maybe in `spec/integration/commands/try_spec.rb`?

**Comment by pdswan** [comment]
Sure thing! Will do that today.

Can use examples to highlight what happens if your block doesn't return a `Result` as well =)

**Comment by pdswan** [comment]
Writing the integration specs made it very clear that not doing *something* about the return values of the blocks passed to `and_then` and `or_else` makes for a pretty poor API.

For now I combined the functionality of Rusts `and_then` with `map` and `or_else` with `map_error`; i.e. if the block returns something that is not of type `ROM::Command::Result` it is automatically wrapped in one.

I'm not a huge fan of the magic of this and I'm sure there are some issues with implementing monadic bind and map as the same function, but I can't think of any right now and I like this better than having to construct a `ROM::Command::Result` every time you use want to use `#and_then`.

**Comment by aflatter** [comment]
Just some ideas.. The challenge is to come up with an API that doesn't feel too alien in the Ruby world.

```ruby
# Option 1
result.and_then do |value|
  if value % 2 == 0
    Error("An even number")
  else
    Ok(value)
  end
end

# Option 2
result.and_then do |value, err, ok|
  if value % 2 == 0
    err["An even number"]
  else
    ok[value]
  end
end

# Option 3
result.and_then do |value|
  if value % 2 == 0
    [:err, "An even number"]
  else
    [:ok, value]
  end
end
```

**Comment by solnic** [comment]
I think option 2 looks good, it's explicit and doesn't require defining global functions. Auto-wrapping does feel like magic that's happening behind the scenes and when you look at `and_then/or_else` blocks it's not obvious that it's going to happen.

**Comment by pdswan** [comment]
Ok, I implemented something close to number 2 but hung both `#success` and `#failure` off of a single passed in dependency:

```ruby
result.and_then do |value, r|
  if value % 2 == 0
    r.failure "An even number"
  else
    r.success value
  end
end
```

Currently, `r` is just `ROM::Commands::Result` to which I've added `.success` and `.failure`.

For kicks, I added a spec for how this affects the implementation's adherence to the monad laws.

It's an easy step away from 2, but now I'm tempted to go all the way and just require folks to do:

```ruby
result.and_then do |value|
  if value % 2 == 0
    ROM::Commands::Result.failure "An even number"
  else
    ROM::Commands::Result.success value
  end
end
```

If we couple this with a runtime error that checks the return value of the block passed to `and_then` or `or_else` we should end up with something pretty user friendly.

But...as I look at this more I think that with [Rust as the example](http://doc.rust-lang.org/0.11.0/std/result/type.Result.html#method.map) `map` and `map_error` may be better for the use case described in #104, especially since I'm a little fuzzy as to whether a `ROM::Commands::Result::Failure` is intended to be manually instantiated without a corresponding `ROM::CommandError`.

I fear I may be in over my head at this point, but I'm happy to continue plugging away/experimenting if you all think it's moving in a valuable direction @solnic @aflatter.

Thanks for entertaining the pull request, very excited about this project!

**Comment by solnic** [comment]
I like yielding result wrapper object to the block; definitely don't like exposing class methods (I'm anti-class interfaces in general).

`Result` could be promoted to be more generic, not strictly related to commands, so that command API can use it, and users can use it too when handling their own error/success cases.

**Pull request closed without merging**
