### PR TITLE
[WIP] Extract changeset files to separate directory

### PR DESCRIPTION
**Pull request by kwngo**
Initial attempt at tackling #399

### CODE REVIEW

**Comment by solnic** [comment]
Great to see this PR opened :) I noticed there's something wrong with code formatting (you can see this in the diff).

**Comment by kwngo** [comment]
@solnic Good catch, I think I fixed them.

**Comment by solnic** [comment]
@kwngo ok looks good, could you also remove that .DS_Store file that got accidentally added to git?

**Comment by solnic** [comment]
This is merged, thank you! <3

**Pull request merged**
