### PR TITLE
Refactor several `method_missing`s to use `fetch` along with `super`

### PR DESCRIPTION
**Pull request by splattael**
/cc @solnic

### CODE REVIEW

**Comment by splattael** [comment]
@solnic I've squashed the commits. This PR is ready to merge.

**Comment by solnic** [comment]
Thanks. Could you also update Changelog that referencing an unknown method in command block will now raise ElementNotFoundError?

**Comment by splattael** [comment]
@solnic Changelog updated :)

**Comment by solnic** [comment]
@splattael awesome thanks!

**Pull request merged**
