### PR TITLE
[WIP] Remove ROM::Config

### PR DESCRIPTION
**Pull request by aflatter**
rom-rails now completely takes care of reading ActiveRecord configuration, so we don't need this in core anymore.

### CODE REVIEW

**Comment by aflatter** [comment]
Specs don't pass yet, as `:adapter` is not supported anymore.

**Comment by aflatter** [comment]
@solnic think you asked about this on Gitter.

**Comment by solnic** [comment]
Right :)

**Comment by solnic** [comment]
w00t

**Pull request merged**
