### PR TITLE
[WIP] Remove descendants tracking

### PR DESCRIPTION
**Pull request by aflatter**
WIP of #142

### CODE REVIEW

**Comment by solnic** [comment]
For now I did [this](https://github.com/rom-rb/rom/commit/68789c76870068432140a3c20678296e14aa678b) - lemme know what you think. I no longer feel super strong about removing inherited-hook "magic" anymore since descendants are part of the setup now.

**Comment by solnic** [comment]
@aflatter I'd like to close this one, :+1: or :-1: ?

**Comment by aflatter** [comment]
I'd say we'll leave it open for now.

**Comment by solnic** [comment]
I believe we gotta think about something more generic here. I see the need for a feature where ROM during setup exposes some interface for gathering information needed to finalize defined classes. I believe this would become even more important when we have some plugin interface in place too.

Maybe we should gather information in a separate issue to see what is needed. The first one is obvious: a list of defined classes.

**Comment by aflatter** [comment]
We talked a little bit about this on Gitter and I think the preferred direction is to have integration gems like `rom-rails` to derive the defined classes from conventions (or policies in yaks speak), right?

**Comment by solnic** [comment]
Yes, I love the policy idea. Would love to have something like that in ROM. Various objects could use different policies, policies could be configured using some top-level interface exposed by `ROM`

**Comment by solnic** [comment]
This is...obsolete. the main idea with explicit registration is still there, I'm gonna describe it in a new issue. Closing this one.

**Pull request closed without merging**
