### PR TITLE
Add support for mapping command results (refs #185)

### PR DESCRIPTION
**Pull request by solnic**
Basically making this work:

``` ruby
rom.command(:users).as(:entity).create[name: 'Jane']
```

### CODE REVIEW

**Comment by AMHOL** [comment]
Nice, looks good

**Comment by solnic** [comment]
@cflipse @aflatter @splattael @gotar @elskwid thoughts? makes sense?

**Comment by aflatter** [comment]
Yes and no. This PR fits the way ROM currently works, but I'm not sure what I think about specifying the same mappers over and over again for each query or command that you do. I'd vote for merging though because I do stuff like `Foo.new(rom.command(:create).call(...))`.

**Comment by solnic** [comment]
we can extend command class definitions so that you can specify which mapper should always be used; however, I'd like to try to get away without having that and simply do that in my code like that:

``` ruby
# excuse me lack of a nice DI :P
class SomeObjectThatPersistsUserDataAndReturnsEntity
  def self.build
    new(ROM.env.command(:users).as(:entity).create)
  end

  def initialize(command)
    @command = command
  end

  def call(input)
    command.call(input)
  end
end
```

In general...that's how ROM is intended to be used, same applies to relations.

**Comment by gotar** [comment]
I like it +1 its a little strand you call mapper before create command but can live with it +1

**Comment by solnic** [comment]
It's actually not strange, it's inline with relation mapping - you can grab command registry and every command that it returns will use the mapper vs setting mapper for each command separately. It's actually more convenient to use it like that.

**Comment by solnic** [comment]
One more thing - we could consider doing the `result :one, as: :entity` which would set `mapper_name` (or something) internally and then `CommandRegistry` could look if this option is set and automatically set that mapper for a particular command.

**Comment by gotar** [comment]
`result :one, as: :entity` - +1

**Pull request merged**
