### PR TITLE
Add ROM::NoAssociationError

### PR DESCRIPTION
**Pull request by pdswan**
in order to enable work toward https://github.com/rom-rb/rom/issues/173

### CODE REVIEW

**Comment by solnic** [comment]
Hm are we sure we want to have that error defined here?

**Comment by pdswan** [comment]
My assumption was that all adapters (sql, mongo, yaml, redis, etc) support associations so all adapters may raise this error. If that's the case I thought it made sense for the error to live with the other top-level errors, but maybe that's incorrect?

**Comment by solnic** [comment]
The only place where we have "association" concept is rom-sql at the moment. Hence my question.

**Comment by pdswan** [comment]
ok, cool. i'll move it over there.

**Pull request closed without merging**
