### PR TITLE
Rename repository

### PR DESCRIPTION
**Pull request by cflipse**
Repository => Gateway, with appropriate deprecation and transitional classes.

### CODE REVIEW

**Comment by solnic** [comment]
@cflipse <3 that was a massive PR :)

**Comment by splattael** [comment]
Thank you so much :+1: :green_heart:

**Comment by solnic** [comment]
@cflipse I just went through 90% of adapters and did the rename there, all went smooth!

**Comment by cflipse** [comment]
Excellent.  :D

**Comment by solnic** [comment]
Correction - 100% of adapters are updated now and roda/lotus/rails too

**Pull request merged**
