### PR TITLE
Allow for configurable component_dirs in auto_registration setup

### PR DESCRIPTION
**Pull request by AMHOL**

### CODE REVIEW

**Comment by solnic** [comment]
I thought this was addressing the namespace issue but it looks like it's a whole new feature :) I'm wondering though why and where do we need this?

**Comment by AMHOL** [comment]
It was part of the problem @skrypalyk had with rom-rails yesterday, regarding already having a commands directory, plus I think it should be configurable anyway :p

**Comment by AMHOL** [comment]
What's the namespace issue BTW?

**Comment by solnic** [comment]
> It was part of the problem @skrypalyk had with rom-rails yesterday, regarding already having a commands directory, plus I think it should be configurable anyway :p

Oh so having that configurable would fix something in rom-rails? I'm not against this feature, just wanted to know where and how it'd be used.

> What's the namespace issue BTW?

dis one https://github.com/rom-rb/rom/pull/338

**Comment by skrypalyk** [comment]
Thank you for doing this @AMHOL! I really appreciate it.

**Comment by AMHOL** [comment]
NP, still needs an update in rom-rails after merge

**Pull request merged**
